[package]
name = "libre-timecode-programmer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.27", features = ["derive"] }
crossterm = "0.28.1"
ratatui = "0.29.0"
rodio = "0.20.1"
